### ISSUE TITLE
Crash frequency in a short time

### ISSUE THREAD

**Issue by lystormenvoy** [pingostack/pingos#102]
Nginx sometimes crash continuously in a short time.
I usually happen after excute `./nginx -s reload`

![image](https://user-images.githubusercontent.com/6795312/207486733-8119624a-4795-4fba-a91c-60d4d5056abe.png)
![image](https://user-images.githubusercontent.com/6795312/207495811-9aed5c13-17f3-4092-8df9-435ecb14e785.png)

The backtrace:
````
#0  0x0000000000464af6 in ngx_log_error_core (level=8, log=0x3c80ee8, err=<optimized out>, fmt=0x7ffe07891de3 "") at src/core/ngx_log.c:168
#1  0x00000000004873d7 in ngx_memalign (alignment=16, size=4096, log=0x3c80ee8) at src/os/unix/ngx_alloc.c:65
#2  0x000000000046508f in ngx_palloc_block (pool=0x4103d50, size=96) at src/core/ngx_palloc.c:186
#3  0x000000000046527f in ngx_palloc_small (align=1, size=<optimized out>, pool=<optimized out>) at src/core/ngx_palloc.c:173
#4  ngx_palloc (pool=<optimized out>, size=<optimized out>) at src/core/ngx_palloc.c:127
#5  0x0000000000465342 in ngx_pcalloc (pool=<optimized out>, size=96) at src/core/ngx_palloc.c:302
#6  0x0000000000554c08 in ngx_rtmp_shared_alloc_mpegts_frame (cl=0x0, mandatory=0) at ../nginx-rtmp-module/ngx_rtmp_shared_module.c:329
#7  0x000000000055d7f0 in ngx_mpegts_live_h264_handler (f=0x7ffe07892870, s=0x41071b0) at ../nginx-rtmp-module/mpegts/ngx_mpegts_live_module.c:1350
#8  ngx_mpegts_live_av (s=0x41071b0, h=<optimized out>, in=<optimized out>) at ../nginx-rtmp-module/mpegts/ngx_mpegts_live_module.c:1662
#9  0x000000000053186a in ngx_rtmp_receive_message (s=0x41071b0, h=0x381a750, in=0x3c681a0) at ../nginx-rtmp-module/ngx_rtmp_handler.c:875
#10 0x000000000053262e in ngx_rtmp_recv (rev=<optimized out>) at ../nginx-rtmp-module/ngx_rtmp_handler.c:486
#11 0x000000000048e148 in ngx_epoll_process_events (cycle=0x3849610, timer=<optimized out>, flags=<optimized out>) at src/event/modules/ngx_epoll_module.c:901
#12 0x0000000000483747 in ngx_process_events_and_timers (cycle=0x3849610) at src/event/ngx_event.c:248
#13 0x000000000048bc23 in ngx_worker_process_cycle (cycle=0x3849610, data=<optimized out>) at src/os/unix/ngx_process_cycle.c:721
#14 0x000000000048a310 in ngx_spawn_process (cycle=0x3849610, proc=0x48bb90 <ngx_worker_process_cycle>, data=0x0, name=0x75143d "worker process", respawn=-4)
    at src/os/unix/ngx_process.c:199
#15 0x000000000048b083 in ngx_st
[corefile.tar.gz](https://github.com/pingostack/pingos/files/10223579/corefile.tar.gz)
art_worker_processes (cycle=0x3849610, n=1, type=-4) at src/os/unix/ngx_process_cycle.c:344
#16 0x000000000048c978 in ngx_master_process_cycle (cycle=0x3849610) at src/os/unix/ngx_process_cycle.c:234
#17 0x0000000000463f1c in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:383

````

or

````
#0  0x0000000000464af6 in ngx_log_error_core (level=8, log=0x3c80ee8, err=<optimized out>, fmt=0x7ffe07891ec3 "") at src/core/ngx_log.c:168
#1  0x00000000004873d7 in ngx_memalign (alignment=16, size=4096, log=0x3c80ee8) at src/os/unix/ngx_alloc.c:65
#2  0x000000000046508f in ngx_palloc_block (pool=0x4103d50, size=72) at src/core/ngx_palloc.c:186
#3  0x000000000046527f in ngx_palloc_small (align=1, size=<optimized out>, pool=<optimized out>) at src/core/ngx_palloc.c:173
#4  ngx_palloc (pool=<optimized out>, size=<optimized out>) at src/core/ngx_palloc.c:127
#5  0x0000000000465342 in ngx_pcalloc (pool=<optimized out>, size=72) at src/core/ngx_palloc.c:302
#6  0x0000000000554e04 in ngx_rtmp_shared_alloc_frame (size=4096, cl=0x3c681a0, mandatory=0) at ../nginx-rtmp-module/ngx_rtmp_shared_module.c:229
#7  0x000000000053c754 in ngx_rtmp_live_av (s=0x41071b0, h=0x381a720, in=0x3c681a0) at ../nginx-rtmp-module/ngx_rtmp_live_module.c:773
#8  0x000000000053186a in ngx_rtmp_receive_message (s=0x41071b0, h=0x381a720, in=0x3c681a0) at ../nginx-rtmp-module/ngx_rtmp_handler.c:875
#9  0x000000000053262e in ngx_rtmp_recv (rev=<optimized out>) at ../nginx-rtmp-module/ngx_rtmp_handler.c:486
#10 0x000000000048e148 in ngx_epoll_process_events (cycle=0x3849610, timer=<optimized out>, flags=<optimized out>) at src/event/modules/ngx_epoll_module.c:901
#11 0x0000000000483747 in ngx_process_events_and_timers (cycle=0x3849610) at src/event/ngx_event.c:248
#12 0x000000000048bc23 in ngx_worker_process_cycle (cycle=0x3849610, data=<optimized out>) at src/os/unix/ngx_process_cycle.c:721
#13 0x000000000048a310 in ngx_spawn_process (cycle=0x3849610, proc=0x48bb90 <ngx_worker_process_cycle>, data=0x0, name=0x75143d "worker process", respawn=3)
    at src/os/unix/ngx_process.c:199
#14 0x000000000048c6ab in ngx_reap_children (cycle=0x3849610) at src/os/unix/ngx_process_cycle.c:598
#15 ngx_master_process_cycle (cycle=0x3849610) at src/os/unix/ngx_process_cycle.c:174
#16 0x0000000000463f1c in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:383

````

[corefile.tar.gz](https://github.com/pingostack/pingos/files/10223585/corefile.tar.gz)

**Comment by lystormenvoy** [comment]
Some logs when crash:

````
2022/12/14 10:11:09 [info] 14620#0: *125319 sps codec: avc header profile=100, compat=0, level=42, nal_bytes=4, ref_frames=66, width=128, height=2144, client: 192.168.35.204, server: 0.0.0.0:1935, session: 0000000003699120, stream: default/hls/university_273
2022/12/14 10:11:09 [info] 14620#0: *125319 receive video header, client: 192.168.35.204, server: 0.0.0.0:1935, session: 0000000003699120, stream: default/hls/university_273
2022/12/14 10:11:09 [info] 14620#0: *125319 receive audio header, client: 192.168.35.204, server: 0.0.0.0:1935, session: 0000000003699120, stream: default/hls/university_273
2022/12/14 10:11:12 [notice] 11637#0: signal 17 (SIGCHLD) received from 14620
2022/12/14 10:11:12 [alert] 11637#0: worker process 14620 exited on signal 11 (core dumped)
2022/12/14 10:11:12 [notice] 11637#0: start worker process 14663
2022/12/14 10:11:12 [notice] 11637#0: signal 29 (SIGIO) received
2022/12/14 10:11:13 [info] 14663#0: *125320 client connected '192.168.35.204'
2022/12/14 10:11:13 [info] 14663#0: *125320 rtmp publish filter, client: 192.168.35.204, server: 0.0.0.0:1935, session: 0000000003699120

````
