### ISSUE TITLE
core  dumped when compile with nginx 1.23.1

### ISSUE THREAD

**Issue by lystormenvoy** [pingostack/pingos#98]
Since nginx change  the number of argument in `ngx_http_variable_unknown_header` function
It print this error when compile :
![image](https://user-images.githubusercontent.com/6795312/182110933-0baf0ab3-bf8f-4970-9145-385d5e0315ee.png)

I add the argument `r` before `&v` and then it can finish compiling.

But it core dumped when client try to play flv stream.
Backtrace:
````
#0  ngx_http_destination_charset (name=0x7ffea4a2bb40, r=0x317f370) at src/http/modules/ngx_http_charset_filter_module.c:330
#1  ngx_http_charset_header_filter (r=0x317f370) at src/http/modules/ngx_http_charset_filter_module.c:225
#2  0x00000000004d0ae7 in ngx_http_sub_header_filter (r=0x317f370) at src/http/modules/ngx_http_sub_filter_module.c:186
#3  0x00000000004d107e in ngx_http_addition_header_filter (r=<optimized out>) at src/http/modules/ngx_http_addition_filter_module.c:108
#4  0x00000000004d1974 in ngx_http_userid_filter (r=<optimized out>) at src/http/modules/ngx_http_userid_filter_module.c:239
#5  0x00000000004d2c47 in ngx_http_headers_filter (r=<optimized out>) at src/http/modules/ngx_http_headers_filter_module.c:243
#6  0x000000000052598f in ngx_http_broadcast_header_filter (r=0x317f370) at ../nginx-multiport-module/ngx_http_broadcast_module.c:182
#7  0x0000000000525e17 in ngx_http_inner_proxy_header_filter (r=<optimized out>) at ../nginx-multiport-module/ngx_http_inner_proxy_module.c:134
#8  0x00000000004d35a4 in ngx_http_not_modified_header_filter (r=<optimized out>) at src/http/modules/ngx_http_not_modified_filter_module.c:108
#9  0x00000000004d3846 in ngx_http_slice_header_filter (r=0x317f370) at src/http/modules/ngx_http_slice_filter_module.c:113
#10 0x000000000049ea8c in ngx_http_send_header (r=r@entry=0x317f370) at src/http/ngx_http_core_module.c:1852
#11 0x0000000000568554 in ngx_http_flv_live_send_header (r=0x317f370) at ../nginx-rtmp-module/http/ngx_http_flv_live_module.c:137
#12 ngx_http_flv_live_write_handler (r=0x317f370) at ../nginx-rtmp-module/http/ngx_http_flv_live_module.c:362
#13 0x00000000004a2e24 in ngx_http_request_handler (ev=0x7f101e34f250) at src/http/ngx_http_request.c:2386
#14 0x000000000048105f in ngx_event_process_posted (cycle=cycle@entry=0x317a350, posted=0x23dd630 <ngx_posted_events>) at src/event/ngx_event_posted.c:34
#15 0x0000000000480b7e in ngx_process_events_and_timers (cycle=cycle@entry=0x317a350) at src/event/ngx_event.c:263
#16 0x000000000048929e in ngx_worker_process_cycle (cycle=cycle@entry=0x317a350, data=data@entry=0x0) at src/os/unix/ngx_process_cycle.c:721
#17 0x000000000048795d in ngx_spawn_process (cycle=cycle@entry=0x317a350, proc=0x48920b <ngx_worker_process_cycle>, data=0x0, name=0x769f3e "worker process", 
    respawn=respawn@entry=0) at src/os/unix/ngx_process.c:199
#18 0x0000000000489f53 in ngx_reap_children (cycle=0x317a350) at src/os/unix/ngx_process_cycle.c:598
#19 ngx_master_process_cycle (cycle=cycle@entry=0x317a350) at src/os/unix/ngx_process_cycle.c:174
#20 0x0000000000460ab1 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:383

````

**Comment by elvizlai** [comment]
+1

**Comment by lystormenvoy** [comment]
> [nginx-toolkit-module](https://github.com/pingostack/pingos/tree/master/modules/nginx-toolkit-module)
> 
> +1

也不算难，ngx_http_variable_unknown_header函数加了一个ngx_http_request_t 参数在第一个参数位置，修改编译错误的那个文件在调用那加个r就能编译过了

**Comment by ICe120566** [comment]
修改后可以编译通过，rtmp流可以拉取，但是hls+流拉取存在问题。

**Comment by lystormenvoy** [comment]
> 修改后可以编译通过，rtmp流可以拉取，但是hls+流拉取存在问题。

我试了flv流拉不了我记得

**Comment by ICe120566** [comment]
> > 修改后可以编译通过，rtmp流可以拉取，但是hls+流拉取存在问题。
> 
> 我试了flv流拉不了我记得

是的，http的流应该都拉不了，会导致数据中断，后来此问题有解决么？

**Comment by lystormenvoy** [comment]
> > > 修改后可以编译通过，rtmp流可以拉取，但是hls+流拉取存在问题。
> > 
> > 
> > 我试了flv流拉不了我记得
> 
> 是的，http的流应该都拉不了，会导致数据中断，后来此问题有解决么？

放弃了

**Comment by im-pingo** [comment]
> > > > 修改后可以编译通过，rtmp流可以拉取，但是hls+流拉取存在问题。
> > > 
> > > 
> > > 我试了flv流拉不了我记得
> > 
> > 
> > 是的，http的流应该都拉不了，会导致数据中断，后来此问题有解决么？
> 
> 放弃了

给我两个月时间，我在写新服务，争取今年把陈旧的pingos服务转生

**Comment by liubing-sky** [comment]
后来有更新么？1年过去了

**Comment by lystormenvoy** [comment]
> 后来有更新么？1年过去了

没有，这种大改动我搞不来。作者开新坑了，这个估计不维护了。
